# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 2.0.0
maven_group = com.finndog
archives_name = litematicatool
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 1.20.5

# Dependencies
fabric_loader_version = 0.17.2
fabric_api_version = 0.97.8+1.20.5
neoforge_version = 20.5.21-beta