modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "litematicatool"
version = "${version}"
displayName = "LitematicaTool"
authors = "FinnDog"
description = '''
A simple tool designed to work with Litematica for enhanced schematic management.
'''
#logoFile = ""

[[dependencies.litematicatool]]
modId = "neoforge"
type = "required"
versionRange = "[21.11,21.12)"
ordering = "NONE"
side = "BOTH"

[[dependencies.litematicatool]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.11,1.22)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "litematicatool.mixins.json"
