name: Build

on:
  push:
    branches: ['**']
    tags-ignore: ['*.*.*-*.*.*']
  pull_request:
    branches: ['**']

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        shell: bash
        run: |
          set -eo pipefail
          chmod +x gradlew
          ./gradlew :fabric:build :neoforge:build
